### ISSUE TITLE
Wrong restart message and release notes not up-to-date

### ISSUE THREAD

**Issue by rugk** [atom/release-notes#39] opened 2015-11-15 20:20 UTC
After updating to Atom v1.2.0:
![wrongrestartmessage](https://cloud.githubusercontent.com/assets/11966684/11163391/9504dccc-8acd-11e5-8ac6-dfd838f223d2.png)

---

Moved from https://github.com/atom/atom/issues/9590

**Comment by cebor** [comment] 2015-11-16 09:18
same issue here

**Comment by JAAdrian** [comment] 2015-11-17 12:32
+1
Windows 7, 64Bit

**Comment by petey** [comment] 2015-11-17 20:50
+1 on OSX, Atom 1.2.1

**Comment by jeffschwartz** [comment] 2015-11-18 01:30
+1 on OSX, Atom v1.2.1

**Comment by Zooce** [comment] 2015-11-18 04:39
+1 on OS X 10.11.1, Atom 1.2.1

**Comment by rugk** [comment] 2015-11-18 10:13
As others already said I can also confirm it with v1.2.1 of Atom (Win7 x64).

**Comment by jeffschwartz** [comment] 2015-11-19 12:58
Just installed Atom update v1.2.2. Release notes plugin still broken.
![screen shot 2015-11-19 at 7 57 02 am](https://cloud.githubusercontent.com/assets/271288/11271342/3f890e70-8e93-11e5-8a57-924290eae64b.png)
![screen shot 2015-11-19 at 7 58 14 am](https://cloud.githubusercontent.com/assets/271288/11271354/53e1a508-8e93-11e5-81f8-fbd745979a18.png)

**Comment by kevwil** [comment] 2015-11-19 16:58
+1 here, just updated to 1.2.2 on OS X 10.10.5 and still broken

**Comment by frankhale** [comment] 2015-11-19 17:19
Reference duplicate issue: https://github.com/atom/atom/issues/3757

**Comment by shaungrady** [comment] 2015-11-19 17:27
+1, Atom 1.2.2, OS X 10.11.1 (15B42)

**Comment by Zooce** [comment] 2015-11-20 03:21
Still happening with 1.2.3 on OS X 10.11.1

**Comment by Hurtak** [comment] 2015-11-20 07:13
Win7 fresh install of Atom 1.2.3

http://i.imgur.com/Bc55FJX.png

**Comment by vinkla** [comment] 2015-11-20 13:44
Experiencing the same issue in Atom `1.2.3` on OS X `10.11.1`.

<img width="487" alt="screen shot 2015-11-20 at 1 40 58 pm" src="https://cloud.githubusercontent.com/assets/499192/11301176/3a20c6b4-8f95-11e5-8fc6-e9a166fadf53.png">

**Comment by Alhadis** [comment] 2015-11-20 14:15
+1, can confirm.

**Comment by rugk** [comment] 2015-11-21 11:28
From https://github.com/atom/atom/issues/3757#issuecomment-158147465 by @benogle

> We're really sorry about this issue. The plan is to remove the release notes package and have all the update logic in the about page similar to chrome. See https://github.com/atom/atom/issues/9164 for more details.

**Comment by opponitur** [comment] 2015-12-11 07:47
+1, OS X 10.11.2(15C50), Atom 1.3.1

**Comment by pistou** [comment] 2015-12-11 14:19
+1, Windows 10, Atom 1.3.1

**Comment by brianmickelson** [comment] 2015-12-16 21:34
+1, Win7, Atom 1.3.2

**Comment by petey** [comment] 2015-12-17 04:40
I think I managed to fix my release notes view by clearing the localStorage cache of the release notes data. I can't reproduce this anymore, so I can't really verify. It may just become stuck at the current state, though.

You may be able to replicate a fix by running `localStorage.removeItem('release-notes:releaseNotes');` in the Javascript console in atom's developer tools, then restart atom.

**Comment by hugokrantz** [comment] 2015-12-17 08:08
@petey That did not work for me. (Latest OS X, latest Atom)

The temporary workaround `localStorage.setItem('release-notes:version', "1.3.2")` works though, so I guess I'll stick to that until this is resolved.

**Comment by petey** [comment] 2015-12-17 13:00
@hugokrantz You are right, as I can set `version` back to 1.1.0 and see this behavior again. So I wonder if there is an issue with this: https://github.com/atom/release-notes/blob/df0de51cdf0719a46873919390c8f70de99ae834/lib/main.coffee#L22 that it does not set `version` properly anymore.

**Comment by Alhadis** [comment] 2015-12-17 13:06
I actually deleted that property from the developer tools' local storage, and it had literally zero impact. Then I tried deleting the cached release notes to see if that had any effect.

Nope, nada. :(

**Comment by frankhale** [comment] 2015-12-17 13:13
This direction that will be taken as far as this issue goes has been mentioned already by Github staff. See the last message on the following issue posted to Atom:

Reference issue: https://github.com/atom/atom/issues/3757

"We're really sorry about this issue. The plan is to remove the release notes package and have all the update logic in the about page similar to chrome. See #9164 for more details."

That issue number referenced in the quote is on Atom.

**Comment by petey** [comment] 2015-12-17 13:20
I totally understand the intended behavior, but until that is actually released, it looks REALLY bad on atom that this is broken. This package has been broken for a little over a month, and looking back at the referenced issue, has regressed from earlier problems.

**Comment by frankhale** [comment] 2015-12-17 13:21
I totally agree with you @petey.

**Comment by alexchandel** [comment] 2015-12-17 14:01
There is a specific issue with 1.1.0 and beyond. The release notes stuck of _every reporter_ in this thread, including me, got stuck at 1.1.0. Only `localStorage.setItem('release-notes:version', "1.3.2")` helps.

**Comment by lee-dohm** [comment] 2018-08-23 19:43
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed as completed by lee-dohm** 2018-08-23 19:43 UTC
Labels: bug
