### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by forbesguthrie** [atom/release-notes#33] opened 2015-02-19 20:12 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.47.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:455

Error: ENOENT, no such file or directory '/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom 2.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (/Applications/Atom 2.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.Module._extensions..js (module.js:485:20)
  at Module.load (/Applications/Atom 2.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom 2.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:14:15)
  at Object.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:70:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom 2.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at convertMarkdown (/Applications/Atom 2.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:73:15)
  at createReleaseNotes (/Applications/Atom 2.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:64:12)
  at Object.$.ajax.success (/Applications/Atom 2.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:22:16)
  at fire (/Applications/Atom 2.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3073:30)
  at Object.self.fireWith [as resolveWith] (/Applications/Atom 2.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3185:7)
  at done (/Applications/Atom 2.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8251:14)
  at XMLHttpRequest.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8598:9)

```

### Commands

```
     -0:31.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 15x -0:25.1 core:backspace (atom-text-editor.editor.mini)
     -0:03.4 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui.find-visible)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "release-notes": {
    "viewedVersion": "0.93.0"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-19 20:13
Duplicate of #29.

**Closed by 50Wliu** 2015-02-19 20:13 UTC
