### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by alexmorken** [atom/release-notes#32] opened 2015-02-18 20:52 UTC
[Enter steps to reproduce below:]

1. Open Editor

**Atom Version**: 0.178.0
**System**: Mac OS X 10.10.2
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.47.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Users/alexm/Downloads/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Users/alexm/Downloads/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/src/6to5.js:136:21)
  at Module.load (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/node_modules/task-lists/lib/index.js:4:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:14:15)
  at Object.<anonymous> (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:70:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/src/6to5.js:138:21)
  at Module.load (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at convertMarkdown (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:73:15)
  at createReleaseNotes (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:64:12)
  at Object.$.ajax.success (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/release-notes/lib/release-notes.js:22:16)
  at fire (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3094:30)
  at Object.self.fireWith [as resolveWith] (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:3206:7)
  at done (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8259:14)
  at XMLHttpRequest.<anonymous> (/Users/alexm/Downloads/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:8600:9)

```

### Commands

```
     -0:13.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  5x -0:10.5 core:backspace (atom-text-editor.editor.mini)
     -0:05.8 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:05.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:05.2 core:cancel (atom-text-editor.editor.mini)
     -0:01.1 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.11.1
linter-python-pep8, v0.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-18 21:03
Duplicate of #29.

**Closed by 50Wliu** 2015-02-18 21:03 UTC
