### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/hamishclulee/Library/Application...

### ISSUE THREAD

**Issue by HamishClulee** [atom/release-notes#41] opened 2015-12-20 19:45 UTC
[Enter steps to reproduce below:]
1. ... opened /docs/getting-started.md downloaded from https://www.reactstarterkit.com/
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [release-notes](https://github.com/atom/release-notes) package, v0.53.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:41)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
    at Module._compile (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:18:28)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/release-notes/lib/release-notes-status-bar.js:6:10)
    at Object.<anonymous> (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/node_modules/release-notes/lib/release-notes-status-bar.js:59:4)
    at Module._compile (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/hamishclulee/Library/Application Support/com.github.atom.ShipIt/update.hsooxRE/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by winstliu** [comment] 2015-12-20 21:51
This is a duplicate of atom/atom#7399 - please subscribe there for updates.

**Closed as completed by winstliu** 2015-12-20 21:51 UTC
Labels: duplicate, wrong-repo
