### ISSUE TITLE
Release Notes not updating on Windows

### ISSUE THREAD

**Issue by steveoh** [atom/release-notes#26] opened 2015-02-03 19:53 UTC
![image](https://cloud.githubusercontent.com/assets/325813/6027996/55238374-aba3-11e4-8664-a7f000ff5d45.png)

I'm on version `0.177.0` but the log has stopped updating since `0.161.0`. I believe this was around the time I migrated from chocolatey. I do not think the `restart and update` button should be visible either. I would assume that is a side affect. 

Thoughts? :checkered_flag:

**Comment by 50Wliu** [comment] 2015-02-03 20:10
Duplicate of atom/atom#3757, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-03 20:10 UTC
